"""whois cache + best snapshot fields

Revision ID: 46755f74e169
Revises: d940d43ff7b6
Create Date: 2026-05-25 19:30:10.219550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46755f74e169'
down_revision: Union[str, None] = 'd940d43ff7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whois_cache',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    with op.batch_alter_table('whois_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whois_cache_fetched_at'), ['fetched_at'], unique=False)

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whois_registration_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('whois_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('whois_fetched_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_snapshot_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('best_snapshot_ts', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('best_snapshot_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('best_snapshot_detail', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.drop_column('best_snapshot_detail')
        batch_op.drop_column('best_snapshot_score')
        batch_op.drop_column('best_snapshot_ts')
        batch_op.drop_column('best_snapshot_url')

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('whois_fetched_at')
        batch_op.drop_column('whois_status')
        batch_op.drop_column('whois_registration_date')

    with op.batch_alter_table('whois_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whois_cache_fetched_at'))

    op.drop_table('whois_cache')
    # ### end Alembic commands ###
