"""initial schema

Revision ID: d940d43ff7b6
Revises: 
Create Date: 2026-05-24 12:46:34.950810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd940d43ff7b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_domains', sa.Integer(), nullable=False),
    sa.Column('processed_domains', sa.Integer(), nullable=False),
    sa.Column('clean_count', sa.Integer(), nullable=False),
    sa.Column('nuanced_count', sa.Integer(), nullable=False),
    sa.Column('dirty_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('verdict_key_flags', sa.JSON(), nullable=True),
    sa.Column('first_capture_at', sa.DateTime(), nullable=True),
    sa.Column('last_capture_at', sa.DateTime(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('total_captures', sa.Integer(), nullable=False),
    sa.Column('total_versions', sa.Integer(), nullable=False),
    sa.Column('risky_flag_count', sa.Integer(), nullable=False),
    sa.Column('review_flag_count', sa.Integer(), nullable=False),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index('ix_domain_run_domain', ['run_id', 'domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_verdict'), ['verdict'], unique=False)

    op.create_table('drops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('gap_from', sa.DateTime(), nullable=False),
    sa.Column('gap_to', sa.DateTime(), nullable=False),
    sa.Column('gap_days', sa.Integer(), nullable=False),
    sa.Column('category_before', sa.String(length=64), nullable=True),
    sa.Column('category_after', sa.String(length=64), nullable=True),
    sa.Column('is_drop', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drops_domain_id'), ['domain_id'], unique=False)

    op.create_table('epochs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.DateTime(), nullable=False),
    sa.Column('period_to', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sample_snapshot_url', sa.Text(), nullable=True),
    sa.Column('versions_in_epoch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epochs_domain_id'), ['domain_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('snapshot_url', sa.Text(), nullable=True),
    sa.Column('input_text_gz', sa.LargeBinary(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_llm_role_model', ['role', 'model'], unique=False)

    op.create_table('redirects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('from_url', sa.Text(), nullable=False),
    sa.Column('to_url', sa.Text(), nullable=True),
    sa.Column('target_domain', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('snapshot_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redirects_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_redirects_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redirects_target_domain'), ['target_domain'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redirects_target_domain'))
        batch_op.drop_index(batch_op.f('ix_redirects_domain_id'))
        batch_op.drop_index(batch_op.f('ix_redirects_classification'))

    op.drop_table('redirects')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_role_model')
        batch_op.drop_index(batch_op.f('ix_llm_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_role'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_model'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_domain_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epochs_domain_id'))

    op.drop_table('epochs')
    with op.batch_alter_table('drops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drops_domain_id'))

    op.drop_table('drops')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_verdict'))
        batch_op.drop_index(batch_op.f('ix_domains_status'))
        batch_op.drop_index(batch_op.f('ix_domains_run_id'))
        batch_op.drop_index(batch_op.f('ix_domains_domain'))
        batch_op.drop_index('ix_domain_run_domain')

    op.drop_table('domains')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_started_at'))

    op.drop_table('runs')
    # ### end Alembic commands ###
